# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'swad.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.forw_but = QtWidgets.QPushButton(Form)
        self.forw_but.setGeometry(QtCore.QRect(150, 40, 100, 50))
        self.forw_but.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"background-color: rgb(87, 227, 137);\n"
"\n"
"QPushButton#forw_but{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#forw_but:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#forw_but:hover{\n"
"background-color: rgb(85, 87, 83);\n"
"}")
        self.forw_but.setObjectName("forw_but")
        self.forw_but_2 = QtWidgets.QPushButton(Form)
        self.forw_but_2.setGeometry(QtCore.QRect(270, 130, 100, 50))
        self.forw_but_2.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"background-color: rgb(53, 132, 228);\n"
"\n"
"QPushButton#forw_but{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#forw_but:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#forw_but:hover{\n"
"background-color: rgb(85, 87, 83);\n"
"}")
        self.forw_but_2.setObjectName("forw_but_2")
        self.forw_but_3 = QtWidgets.QPushButton(Form)
        self.forw_but_3.setGeometry(QtCore.QRect(150, 210, 100, 50))
        self.forw_but_3.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"background-color: rgb(248, 228, 92);\n"
"\n"
"QPushButton#forw_but{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#forw_but:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#forw_but:hover{\n"
"background-color: rgb(85, 87, 83);\n"
"}")
        self.forw_but_3.setObjectName("forw_but_3")
        self.forw_but_4 = QtWidgets.QPushButton(Form)
        self.forw_but_4.setGeometry(QtCore.QRect(40, 130, 100, 50))
        self.forw_but_4.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"background-color: rgb(229, 165, 10);\n"
"\n"
"QPushButton#forw_but{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#forw_but:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#forw_but:hover{\n"
"background-color: rgb(85, 87, 83);\n"
"}")
        self.forw_but_4.setObjectName("forw_but_4")
        self.forw_but_5 = QtWidgets.QPushButton(Form)
        self.forw_but_5.setGeometry(QtCore.QRect(10, 10, 100, 50))
        self.forw_but_5.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"background-color: rgb(246, 97, 81);\n"
"\n"
"QPushButton#forw_but{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#forw_but:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#forw_but:hover{\n"
"background-color: rgb(85, 87, 83);\n"
"}")
        self.forw_but_5.setObjectName("forw_but_5")
        self.back_but = QtWidgets.QPushButton(Form)
        self.back_but.setGeometry(QtCore.QRect(290, 240, 100, 50))
        self.back_but.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"background-color: rgb(246, 97, 81);\n"
"\n"
"QPushButton#forw_but{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#forw_but:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#forw_but:hover{\n"
"background-color: rgb(85, 87, 83);\n"
"}")
        self.back_but.setObjectName("back_but")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.forw_but.setText(_translate("Form", "W"))
        self.forw_but_2.setText(_translate("Form", "D"))
        self.forw_but_3.setText(_translate("Form", "S"))
        self.forw_but_4.setText(_translate("Form", "A"))
        self.forw_but_5.setText(_translate("Form", "Q for quit"))
        self.back_but.setText(_translate("Form", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
